### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by sj14** [Slashgear/action-check-pr-title#72]
Thanks for the great project!

When using the action in the current version 3.0.0, I get the following warning message:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Slashgear/action-check-pr-title
```

![Bildschirmfoto 2022-10-19 um 15 14 43](https://user-images.githubusercontent.com/6493966/196701356-c8361be0-c257-4ca5-9b95-135ceddfdd36.png)

I just wanted to make you aware of this.

**Comment by jagoncalves14** [comment]
@sj14 and @Slashgear, I opened a PR for this:
https://github.com/Slashgear/action-check-pr-title/pull/80

**Comment by Slashgear** [comment]
Thank you a lot for that :ok
