### ISSUE TITLE
feat(error): allow to present some passing examples on failure

### ISSUE THREAD

**Issue by yannbertrand** [Slashgear/action-check-pr-title#93]
**Is your feature request related to a problem? Please describe.**
When the action fails, the log shows the regex that's been used, but a regex is not super easy to read.

**Describe the solution you'd like**
I'd love to add an optional param to display some matching examples.

Example of better log:
```
Error: Pull Request title "(PIX-0000) Linter les titres de PR" failed to pass match regex - /\[[A-Z]+\] .+/

Example of matching titles:
- "[FEATURE] Migration des profils cibles (PIX-6596)"
- "[BUGFIX] Corriger l'erreur d'année sur un test CPF (pix-6704)"
- "[TECH] Linter les titres de PR"
```

Another approach would be to redirect the user to the full rules (e.g.: a CONTRIBUTING.md file).

**Describe alternatives you've considered**
It should be possible to do it on my side by adding a "failure" step that catches the error and logs it itself.

**Additional context**
I've deployed this action in the [Pix project](https://github.com/1024pix/pix/pull/5445) :)

**Comment by Slashgear** [comment]
Nice idea, do you want to work on it ?
I could do that also this does not seem to be really complex :)

**Comment by yannbertrand** [comment]
> Nice idea, do you want to work on it ? I could do that also this does not seem to be really complex :)

Thanks for the quick answer!

Please feel free to do it if you have time. I didn't think of a param name so I'll let you choose one.

**Comment by Slashgear** [comment]
I can and will do it soon.
May I ask your review on it ? 😄

**Comment by yannbertrand** [comment]
> May I ask your review on it ? 😄

Sure 😄

**Comment by Slashgear** [comment]
@yannbertrand Normally this should do it, let me know it this is ok :)
